name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4.1.0
        with:
          java-version: 17

      - name: Decode nework.properties
        env:
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          MAP_KIT_API_KEY: ${{ secrets.MAP_KIT_API_KEY }}
        run: echo $FIREBASE_SECRET > .nework.properties

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build
          
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk      
